### ISSUE TITLE
Reader::from_files should accept an iterator

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winmd-rs#3]
Ideally we can avoid having to create a collection/array to call this function.

Mentioned here: https://github.com/microsoft/winmd-rs/pull/1#pullrequestreview-310601514

**Comment by rylev** [comment]
Since we're [counting the number of `files`](https://github.com/microsoft/winmd-rs/blob/83a3aeb5e2f80794258035a6eafebee0e6af2f52/src/reader.rs#L76), we'll have to consume the iterator anyway. This means we either can know the size of the `files` and be smart about the `databases` allocation OR not be smart about the `databases` allocation and save on temporarily allocating the files into a `Vec`. Given that the current solution is easier to reason about, I would suggest we stick with it.

**Comment by kennykerr** [comment]
Sounds good.
